/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.backend.*;

public class Login extends javax.swing.JFrame {
    Botones btn = new Botones();
    CamposTexto txt = new CamposTexto();

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorde = new javax.swing.JPanel();
        panelFondoPrincipal = new javax.swing.JPanel();
        panelFondoIcono = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botonSiguiente = new javax.swing.JPanel();
        textoBtnSiguiente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorde.setBackground(new java.awt.Color(240, 70, 79));
        panelBorde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoPrincipal.setBackground(new java.awt.Color(142, 180, 98));
        panelFondoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoIcono.setBackground(new java.awt.Color(234, 217, 101));
        panelFondoIcono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Splash.png"))); // NOI18N
        panelFondoIcono.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 340, 290));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 71, 84));
        jLabel2.setText("WELL");
        panelFondoIcono.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 300, 70));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 71, 84));
        jLabel4.setText("EAT");
        panelFondoIcono.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 180, 70));

        panelFondoPrincipal.add(panelFondoIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 570));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 71, 84));
        jLabel3.setText("USUARIO");
        panelFondoPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 350, 70));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 71, 84));
        jLabel5.setText("INICIAR SESIÓN");
        panelFondoPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 350, 70));

        jtxtUsuario.setBackground(new java.awt.Color(142, 181, 113));
        jtxtUsuario.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jtxtUsuario.setText("INGRESE SU USUARIO");
        jtxtUsuario.setBorder(null);
        jtxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtUsuarioMousePressed(evt);
            }
        });
        jtxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsuarioActionPerformed(evt);
            }
        });
        panelFondoPrincipal.add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 380, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panelFondoPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 380, 20));

        botonSiguiente.setBackground(new java.awt.Color(72, 127, 120));
        botonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSiguienteMouseExited(evt);
            }
        });
        botonSiguiente.setLayout(new java.awt.BorderLayout());

        textoBtnSiguiente.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        textoBtnSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBtnSiguiente.setText("SIGUIENTE");
        textoBtnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textoBtnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        textoBtnSiguiente.setVerifyInputWhenFocusTarget(false);
        textoBtnSiguiente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                textoBtnSiguienteMouseMoved(evt);
            }
        });
        textoBtnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textoBtnSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textoBtnSiguienteMouseExited(evt);
            }
        });
        botonSiguiente.add(textoBtnSiguiente, java.awt.BorderLayout.CENTER);

        panelFondoPrincipal.add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 230, 50));

        panelBorde.add(panelFondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 970, 570));

        getContentPane().add(panelBorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoBtnSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoBtnSiguienteMouseEntered
        // TODO add your handling code here:
        btn.cambiarColorBotonLogin(botonSiguiente,0);
    }//GEN-LAST:event_textoBtnSiguienteMouseEntered

    private void textoBtnSiguienteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoBtnSiguienteMouseMoved
        // TODO add your handling code here       
    }//GEN-LAST:event_textoBtnSiguienteMouseMoved

    private void botonSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSiguienteMouseExited
        // TODO add your handling code here: 
    }//GEN-LAST:event_botonSiguienteMouseExited

    private void botonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSiguienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiguienteMouseEntered

    private void textoBtnSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textoBtnSiguienteMouseExited
        // TODO add your handling code here:
        btn.cambiarColorBotonLogin(botonSiguiente,1);
    }//GEN-LAST:event_textoBtnSiguienteMouseExited

    private void jtxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioActionPerformed

    private void jtxtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUsuarioMousePressed
        // TODO add your handling code here:
        txt.textoDefecto(jtxtUsuario);
    }//GEN-LAST:event_jtxtUsuarioMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtxtUsuario;
    private javax.swing.JPanel panelBorde;
    private javax.swing.JPanel panelFondoIcono;
    private javax.swing.JPanel panelFondoPrincipal;
    private javax.swing.JLabel textoBtnSiguiente;
    // End of variables declaration//GEN-END:variables
}
